/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rockman.helloMayor

import com.badlogic.gdx.backends.lwjgl.LwjglApplication
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration

fun main(args: Array<String>) {
    LwjglApplication(GameScene(), LwjglApplicationConfiguration())
}
